name: Create Docker container with smolBSD
on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:

  # Create VM image with all dependencies
  create-vm:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Update Ubuntu dependencies
        run: sudo apt update
      - name: Install Ubuntu dependencies
        run: |
          sudo apt install -y \
             build-essential  \
             curl             \
             git              \
             libarchive-tools \
             qemu-system      \
             rsync            \
             bmake            \
             uuid-runtime

      - name: Create smolBSD image
        run: sudo .github/smol/scripts/create-smolbsd.sh cicd smolBSD
      - name: Remove unnecessary files
        run: sudo rm -rf smolBSD/sets smolBSD/pkgs
      - name: Save image
        uses: actions/upload-artifact@v4
        with:
          path: smolBSD
          name: data

  # Pack VM image inside a container image
  create-docker:
    needs: create-vm
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download image
        uses: actions/download-artifact@v5
        with:
          name: data
          path: smolBSD
      - name: Display structure of downloaded files
        run: ls -R smolBSD

      - name: Log in to the Container registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/open-s4c/dice/smolbsd-ci
          tags: |
            type=edge,branch=dev
            type=raw,latest
            type=sha,format=long

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5.1.0
        with:
          push: true
          context: .
          file: .github/Dockerfile.smolbsd
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
